### ISSUE TITLE
Link to Git-Hub-Pages

### ISSUE THREAD

**Issue by BregornOriginal** [BregornOriginal/Julio-Gagliardi-Portfolio-#12]
### There's the link to the deployment in Git-Hub-Pages!

[Live Demo Link](https://bregornoriginal.github.io/Julio-Gagliardi-Portfolio-/)

**Comment by Ismailco** [comment]
Hi @BregornOriginal,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has a README with the wrong link to the live site on Github pages.
 - Your README on the main branch doesn't have the correct link to the live version, Please create a Pull request from ```my-portfolio-demo``` branch and try to submit the PR with the changes again 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by BregornOriginal** [comment]
Hi @Ismailco ,

Ok! I understand. You're right. I'm creating a PR whit the correct link. 

Thank you for the review!

**Comment by BregornOriginal** [comment]
Resolved!
