### ISSUE TITLE
Bugs on the findig-bugs branch

### ISSUE THREAD

**Issue by KaskMIL** [BregornOriginal/Julio-Gagliardi-Portfolio-#24]
#In this issue I'm going to explain and fix the bugs that I find
- Line 187, in the for loop, the variable $buttonsPopup should have an **i** inside the brackets, because the cards popup is not showing up.
- Line 210, there is a missing **@** inside the regex, because the email is not geting valid.
- line 215, the variable is a misspelling, it should say valid and it says viad. 
- Line 232, the second parameter in the function **showError** is missing and is not showing a message when the email is invalid.

**Hope could I found all the bugs in your code, it was funny! 😸 **

**Comment by HansZizold** [comment]
Dear Julio, thank you very much for helping to complete this exercise. 
After checking your JS code I found the following bugs for your consideration:

Line 205 in the following part: "const $UserEmailElement = document.querySelector('#email-addres');" the ID is missing an 's' in his name, '#email-adress' is the correct ID according to your html file.
Lines 198 and 199: you need to correct the class from 'blu' to 'blur'.
Line 213: the correct name of the variable is 'valid' instead of 'vaid'.

Regards and I hope I found all the bugs.
